services:
  postgres:
    image: postgres:latest
    container_name: some-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: