"""change user relationship with password_reset_token to one-to-one

Revision ID: 0dd42db3d5f3
Revises: c40ddaf8cad7
Create Date: 2026-03-31 14:13:52.758266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0dd42db3d5f3"
down_revision: Union[str, Sequence[str], None] = "c40ddaf8cad7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
