"""add cascade for like field

Revision ID: 1957559ffa5d
Revises: 69ff8189b0e9
Create Date: 2026-05-05 11:18:20.867041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1957559ffa5d'
down_revision: Union[str, Sequence[str], None] = '69ff8189b0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('likes_movies_user_id_fkey'), 'likes_movies', type_='foreignkey')
    op.drop_constraint(op.f('likes_movies_movie_id_fkey'), 'likes_movies', type_='foreignkey')
    op.create_foreign_key(None, 'likes_movies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes_movies', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes_movies', type_='foreignkey')
    op.drop_constraint(None, 'likes_movies', type_='foreignkey')
    op.create_foreign_key(op.f('likes_movies_movie_id_fkey'), 'likes_movies', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('likes_movies_user_id_fkey'), 'likes_movies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
