"""create dislike_comment table

Revision ID: 40c2bd694973
Revises: 3fbe4533936c
Create Date: 2026-04-15 19:36:41.696610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c2bd694973'
down_revision: Union[str, Sequence[str], None] = '3fbe4533936c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', name='user_comment_dislike_uc')
    )
    op.create_unique_constraint('user_movie_dislike_uc', 'dislikes_movies', ['user_id', 'movie_id'])
    op.create_unique_constraint('user_movie_like_uc', 'likes_movies', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_movie_like_uc', 'likes_movies', type_='unique')
    op.drop_constraint('user_movie_dislike_uc', 'dislikes_movies', type_='unique')
    op.drop_table('dislikes_comments')
    # ### end Alembic commands ###
