"""change expired_at field to datetime

Revision ID: 4505dbb34cd3
Revises: 842d99d38957
Create Date: 2026-03-30 13:47:13.164048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4505dbb34cd3'
down_revision: Union[str, Sequence[str], None] = '842d99d38957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activation_tokens', 'expires_at',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using = "to_timestamp(expires_at)")
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="to_timestamp(expires_at)")
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="to_timestamp(expires_at)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="extract(epoch from expires_at)::integer")

    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="extract(epoch from expires_at)::integer")
    op.alter_column('activation_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="extract(epoch from expires_at)::integer")
    # ### end Alembic commands ###
