"""change reply comment foreign key

Revision ID: 52b5be693b2f
Revises: 339ba101af19
Create Date: 2026-04-15 17:14:23.464664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b5be693b2f'
down_revision: Union[str, Sequence[str], None] = '339ba101af19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reply_comments_comment_id_fkey'), 'reply_comments', type_='foreignkey')
    op.create_foreign_key(None, 'reply_comments', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply_comments', type_='foreignkey')
    op.create_foreign_key(op.f('reply_comments_comment_id_fkey'), 'reply_comments', 'movies', ['comment_id'], ['id'])
    # ### end Alembic commands ###
