"""change status_enum to order_status_enum

Revision ID: 5354474df239
Revises: 75a57f6d2d17
Create Date: 2026-04-14 09:46:46.221313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5354474df239'
down_revision: Union[str, Sequence[str], None] = '75a57f6d2d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


order_status_enum = postgresql.ENUM('pending', 'shipped', 'delivered', name='orderstatusenum')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
