"""change column names m2m tables

Revision ID: 555e73327e69
Revises: a4272f4244e2
Create Date: 2026-04-07 21:36:22.086567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "555e73327e69"
down_revision: Union[str, Sequence[str], None] = "a4272f4244e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movie_directors", sa.Column("movies_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "movie_directors", sa.Column("directors_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("movie_directors_left_id_fkey"), "movie_directors", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movie_directors_right_id_fkey"), "movie_directors", type_="foreignkey"
    )
    op.create_foreign_key(None, "movie_directors", "movies", ["movies_id"], ["id"])
    op.create_foreign_key(
        None, "movie_directors", "directors", ["directors_id"], ["id"]
    )
    op.drop_column("movie_directors", "left_id")
    op.drop_column("movie_directors", "right_id")
    op.add_column("movie_genres", sa.Column("movies_id", sa.Integer(), nullable=False))
    op.add_column("movie_genres", sa.Column("genres_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("movie_genres_right_id_fkey"), "movie_genres", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movie_genres_left_id_fkey"), "movie_genres", type_="foreignkey"
    )
    op.create_foreign_key(None, "movie_genres", "genres", ["genres_id"], ["id"])
    op.create_foreign_key(None, "movie_genres", "movies", ["movies_id"], ["id"])
    op.drop_column("movie_genres", "left_id")
    op.drop_column("movie_genres", "right_id")
    op.add_column("movie_stars", sa.Column("movies_id", sa.Integer(), nullable=False))
    op.add_column("movie_stars", sa.Column("stars_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("movie_stars_right_id_fkey"), "movie_stars", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movie_stars_left_id_fkey"), "movie_stars", type_="foreignkey"
    )
    op.create_foreign_key(None, "movie_stars", "stars", ["stars_id"], ["id"])
    op.create_foreign_key(None, "movie_stars", "movies", ["movies_id"], ["id"])
    op.drop_column("movie_stars", "left_id")
    op.drop_column("movie_stars", "right_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movie_stars",
        sa.Column("right_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "movie_stars",
        sa.Column("left_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "movie_stars", type_="foreignkey")
    op.drop_constraint(None, "movie_stars", type_="foreignkey")
    op.create_foreign_key(
        op.f("movie_stars_left_id_fkey"), "movie_stars", "movies", ["left_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("movie_stars_right_id_fkey"), "movie_stars", "stars", ["right_id"], ["id"]
    )
    op.drop_column("movie_stars", "stars_id")
    op.drop_column("movie_stars", "movies_id")
    op.add_column(
        "movie_genres",
        sa.Column("right_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "movie_genres",
        sa.Column("left_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "movie_genres", type_="foreignkey")
    op.drop_constraint(None, "movie_genres", type_="foreignkey")
    op.create_foreign_key(
        op.f("movie_genres_left_id_fkey"), "movie_genres", "movies", ["left_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("movie_genres_right_id_fkey"),
        "movie_genres",
        "genres",
        ["right_id"],
        ["id"],
    )
    op.drop_column("movie_genres", "genres_id")
    op.drop_column("movie_genres", "movies_id")
    op.add_column(
        "movie_directors",
        sa.Column("right_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "movie_directors",
        sa.Column("left_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "movie_directors", type_="foreignkey")
    op.drop_constraint(None, "movie_directors", type_="foreignkey")
    op.create_foreign_key(
        op.f("movie_directors_right_id_fkey"),
        "movie_directors",
        "directors",
        ["right_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("movie_directors_left_id_fkey"),
        "movie_directors",
        "movies",
        ["left_id"],
        ["id"],
    )
    op.drop_column("movie_directors", "directors_id")
    op.drop_column("movie_directors", "movies_id")
    # ### end Alembic commands ###
