"""change gt to ge meta_score check constraint

Revision ID: 5a3f3c1b9cc8
Revises: 9a02a1206b09
Create Date: 2026-05-01 16:45:48.655900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3f3c1b9cc8'
down_revision: Union[str, Sequence[str], None] = '9a02a1206b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("meta_score_gt_0", "movies", type_="check"),
    op.create_check_constraint(
        "meta_score_ge_0",
        "movies",
        "meta_score >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("meta_score_ge_0", "movies", type_="check"),
    op.create_check_constraint(
        "meta_score_gt_0",
        "movies",
        "meta_score > 0"
    ),
    # ### end Alembic commands ###
