"""add unique_constraint to like class

Revision ID: 60753a60dfc0
Revises: 6e5589ac72b0
Create Date: 2026-04-06 19:49:52.989530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60753a60dfc0'
down_revision: Union[str, Sequence[str], None] = '6e5589ac72b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('user_movie_uc', 'likes', ['user_id', 'movie_id'])
    op.drop_constraint(op.f('likes_movies_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'movies', ['movie_id'], ['id'])
    op.drop_column('likes', 'movies_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('movies_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_movies_id_fkey'), 'likes', 'movies', ['movies_id'], ['id'])
    op.drop_constraint('user_movie_uc', 'likes', type_='unique')
    op.drop_column('likes', 'movie_id')
    # ### end Alembic commands ###
