"""add director_id column to movie table

Revision ID: 610160417742
Revises: 76fd466f26cf
Create Date: 2026-04-13 10:46:54.655455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "610160417742"
down_revision: Union[str, Sequence[str], None] = "76fd466f26cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movies", type_="foreignkey")
    op.drop_column("movies", "director_id")
    # ### end Alembic commands ###
