"""delete reply_comment class, create reply_comment_id foreign key

Revision ID: 6151108d9252
Revises: 40c2bd694973
Create Date: 2026-04-16 08:47:28.786693

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6151108d9252"
down_revision: Union[str, Sequence[str], None] = "40c2bd694973"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reply_comments")
    op.add_column(
        "comments", sa.Column("reply_comment_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "comments", "comments", ["reply_comment_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "reply_comment_id")
    op.create_table(
        "reply_comments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("comment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["comments.id"], name=op.f("reply_comments_comment_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("reply_comments_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reply_comments_pkey")),
    )
    # ### end Alembic commands ###
