"""change user to profile

Revision ID: 631f5a256b30
Revises: 779eac054902
Create Date: 2026-04-06 12:50:56.589001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "631f5a256b30"
down_revision: Union[str, Sequence[str], None] = "779eac054902"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("movie_likes_right_id_fkey"), "movie_likes", type_="foreignkey"
    )
    op.create_foreign_key(None, "movie_likes", "profiles", ["right_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movie_likes", type_="foreignkey")
    op.create_foreign_key(
        op.f("movie_likes_right_id_fkey"), "movie_likes", "users", ["right_id"], ["id"]
    )
    # ### end Alembic commands ###
