"""return imdb field with server_default 0

Revision ID: 69ff8189b0e9
Revises: 67b5e9423d31
Create Date: 2026-05-01 17:07:32.382277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "69ff8189b0e9"
down_revision: Union[str, Sequence[str], None] = "67b5e9423d31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies", sa.Column("imdb", sa.Float(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "imdb")
    # ### end Alembic commands ###
