"""create like class

Revision ID: 6e5589ac72b0
Revises: bcb62ba051ef
Create Date: 2026-04-06 19:29:56.515903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5589ac72b0'
down_revision: Union[str, Sequence[str], None] = 'bcb62ba051ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movies_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movie_likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_likes',
    sa.Column('left_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('right_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['movies.id'], name=op.f('movie_likes_left_id_fkey')),
    sa.ForeignKeyConstraint(['right_id'], ['users.id'], name=op.f('movie_likes_right_id_fkey')),
    sa.PrimaryKeyConstraint('left_id', 'right_id', name=op.f('movie_likes_pkey'))
    )
    op.drop_table('likes')
    # ### end Alembic commands ###
