"""change movie-director to many-to-many relationship

Revision ID: 76dd903fa1af
Revises: 610160417742
Create Date: 2026-04-13 11:17:43.077515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "76dd903fa1af"
down_revision: Union[str, Sequence[str], None] = "610160417742"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_directors",
        sa.Column("movies_id", sa.Integer(), nullable=False),
        sa.Column("directors_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["directors_id"],
            ["directors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movies_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("movies_id", "directors_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_directors")
    # ### end Alembic commands ###
