"""change movie-director to one-to-one relationship

Revision ID: 76fd466f26cf
Revises: 555e73327e69
Create Date: 2026-04-13 10:45:21.177637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "76fd466f26cf"
down_revision: Union[str, Sequence[str], None] = "555e73327e69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_directors")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_directors",
        sa.Column("movies_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("directors_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["directors_id"],
            ["directors.id"],
            name=op.f("movie_directors_directors_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["movies_id"], ["movies.id"], name=op.f("movie_directors_movies_id_fkey")
        ),
    )
    # ### end Alembic commands ###
