"""add like field

Revision ID: 779eac054902
Revises: 6188b8419c34
Create Date: 2026-04-06 12:47:52.726251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "779eac054902"
down_revision: Union[str, Sequence[str], None] = "6188b8419c34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_likes",
        sa.Column("left_id", sa.Integer(), nullable=False),
        sa.Column("right_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("left_id", "right_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_likes")
    # ### end Alembic commands ###
