"""add movie, certification, director, genre, star

Revision ID: 923d62321f21
Revises: b2bcbbc8dc4e
Create Date: 2026-04-05 17:24:21.439169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923d62321f21'
down_revision: Union[str, Sequence[str], None] = 'b2bcbbc8dc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
