"""add check_constraint for imdb field

Revision ID: 9a02a1206b09
Revises: f219bc999c0c
Create Date: 2026-05-01 16:32:56.123688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9a02a1206b09"
down_revision: Union[str, Sequence[str], None] = "f219bc999c0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("imdb_le_10", "movies", "imdb <= 10"),
    op.create_check_constraint("imdb_ge_0", "movies", "imdb >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("imdb_le_10", "movies", type_="check"),
    op.drop_constraint("imdb_ge_0", "movies", type_="check")
    # ### end Alembic commands ###
