"""create movies_users_who_add_to_favourite table with m2m relationship

Revision ID: adef219880e1
Revises: 5354474df239
Create Date: 2026-04-15 12:23:42.001643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adef219880e1'
down_revision: Union[str, Sequence[str], None] = '5354474df239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies_users_who_add_to_favourite',
    sa.Column('movies_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('movies_id', 'users_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_users_who_add_to_favourite')
    # ### end Alembic commands ###
