"""add name_year_time unique constraint

Revision ID: bbc758eca912
Revises: 923d62321f21
Create Date: 2026-04-05 18:22:55.808906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bbc758eca912"
down_revision: Union[str, Sequence[str], None] = "923d62321f21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("name_year_time_uc", "movies", ["name", "year", "time"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("name_year_time_uc", "movies", type_="unique")
    # ### end Alembic commands ###
