"""delete like field

Revision ID: c0532380f328
Revises: 631f5a256b30
Create Date: 2026-04-06 12:55:10.961342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0532380f328'
down_revision: Union[str, Sequence[str], None] = '631f5a256b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_likes',
    sa.Column('left_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('right_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['movies.id'], name=op.f('movie_likes_left_id_fkey')),
    sa.ForeignKeyConstraint(['right_id'], ['profiles.id'], name=op.f('movie_likes_right_id_fkey')),
    sa.PrimaryKeyConstraint('left_id', 'right_id', name=op.f('movie_likes_pkey'))
    )
    # ### end Alembic commands ###
