"""create dislike class, add unique constraint

Revision ID: c33b1843c2db
Revises: 60753a60dfc0
Create Date: 2026-04-07 13:23:15.294987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c33b1843c2db"
down_revision: Union[str, Sequence[str], None] = "60753a60dfc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dislikes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "movie_id", name="user_movie_dislike_uc"),
    )
    op.drop_constraint(op.f("user_movie_uc"), "likes", type_="unique")
    op.create_unique_constraint("user_movie_like_uc", "likes", ["user_id", "movie_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_movie_like_uc", "likes", type_="unique")
    op.create_unique_constraint(
        op.f("user_movie_uc"),
        "likes",
        ["user_id", "movie_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("dislikes")
    # ### end Alembic commands ###
