"""add token_table to db

Revision ID: c38a98e688d5
Revises: 4505dbb34cd3
Create Date: 2026-03-30 14:55:52.141078

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c38a98e688d5"
down_revision: Union[str, Sequence[str], None] = "4505dbb34cd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("activation_tokens_user_id_key"), "activation_tokens", type_="unique"
    )
    op.drop_constraint(
        op.f("password_reset_tokens_user_id_key"),
        "password_reset_tokens",
        type_="unique",
    )
    op.drop_constraint(
        op.f("refresh_tokens_user_id_key"), "refresh_tokens", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("refresh_tokens_user_id_key"),
        "refresh_tokens",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("password_reset_tokens_user_id_key"),
        "password_reset_tokens",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("activation_tokens_user_id_key"),
        "activation_tokens",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
