"""add expired_data_field to token model

Revision ID: c40ddaf8cad7
Revises: a1ff74bea813
Create Date: 2026-03-31 13:56:11.647362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c40ddaf8cad7"
down_revision: Union[str, Sequence[str], None] = "a1ff74bea813"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activation_tokens",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "password_reset_tokens",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "expires_at")
    op.drop_column("password_reset_tokens", "expires_at")
    op.drop_column("activation_tokens", "expires_at")
    # ### end Alembic commands ###
