"""add user extend_existing to usergroup

Revision ID: c7a0b8c457d7
Revises: 9f5160f6054c
Create Date: 2026-04-05 13:11:34.868085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c7a0b8c457d7"
down_revision: Union[str, Sequence[str], None] = "9f5160f6054c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
