"""add check_constraint for meta_score field

Revision ID: f219bc999c0c
Revises: 6151108d9252
Create Date: 2026-05-01 15:05:57.839469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f219bc999c0c"
down_revision: Union[str, Sequence[str], None] = "6151108d9252"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("meta_score_gt_0", "movies", "meta_score > 0"),
    op.create_check_constraint("meta_score_le_100", "movies", "meta_score <= 100")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("meta_score_gt_0", "movies", type_="check"),
    op.drop_constraint("meta_score_le_100", "movies", type_="check")
    # ### end Alembic commands ###
